### ISSUE TITLE
Error resource entity-sync

### ISSUE THREAD

**Issue by Andrea-98** [Underground-Roleplay/framework#62]
![image](https://user-images.githubusercontent.com/15652621/163390474-b36eaea8-07ac-49c3-bd80-8b248746b7d7.png)

**Comment by Andrea-98** [comment]
I use the latest version of the altv server development build and the latest version of nodejs

**Comment by nickplayz** [comment]
Our entity-sync isn't ready for use in dev, if you want to use it in dev you will need to build the packages by yourself.
We use kudze entity-sync 
wrapper https://github.com/Kudze/altv-csharp-entity-sync-to-js-wrapper
