### ISSUE TITLE
ExperimentalWarning: The Node.js specifier resolution in ESM is experimental.

### ISSUE THREAD

**Issue by Megumiii9** [Underground-Roleplay/framework#63]
![image](https://user-images.githubusercontent.com/84313089/163686472-9a942a54-5fb0-4cf6-a6e4-e76f5c2f67b4.png)

I have dependencies completely installed, but I don't know why this is happening, I'm using Node.js V16.14.2.

**Comment by xipanca** [comment]
ignore this error it does not interfere with the functioning of the framework

**Comment by nickplayz** [comment]
warning removed in a70c48c4523e132e53be0b5b164f00148c8a6261
